# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170411_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='city',
        ),
        migrations.RemoveField(
            model_name='question',
            name='country',
        ),
        migrations.RemoveField(
            model_name='question',
            name='zipcode',
        ),
    ]
