# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
